[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
tryrust = "6QS7RtjSAW4Df26qB3nRqAbnr3BzyUehbiWZ1epkMVjF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/frederic/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
