[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
day_2 = "2xFcBC6Bt2VVE7y3zELmFB3QxF6a8xLRDgrJWqK4ukBL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/frederic/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
