[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
day_4 = "CLLW2KDoLHgGfN9H33Xr7iQMtSrPjXxDbD6Zw2FToDeg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/frederic/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
