[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
deploy_tutorial = "5R9eQnyNB5gRoLK1ceqE8cc74BzvzMYxTfbZUpN27psa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/frederic/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
